### ISSUE TITLE
Displaying February broken in TimeTracker Stats

### ISSUE THREAD

**Issue by danielnetresearch** [netresearch/timetracker-ui#2]
If I try to open February in TimeTracker Stats, it jumps to March. If I open the URL for February, the same happens. I logged out and deleted my cookies but the problem reoccurred. I made a video to visualise the problem --> [34_20.zip](https://github.com/netresearch/timetracker-ui/files/3023509/34_20.zip). Chrome (latest) on Windows 10.

**Comment by danielnetresearch** [comment]
Works for me after restarting timetracker-ui, but the problem has been existing for several users for some time.

**Comment by ngolatka** [comment]
Closed due to inactivity.
